import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'

import '@/styles/global.css'
import 'photoswipe/dist/photoswipe.css'
import 'react-toastify/dist/ReactToastify.css'

import { Flip, ToastContainer } from 'react-toastify'
import Head from 'next/head'

// const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={lexend.className}>
          {children}
          <ToastContainer
            style={{ fontFamily: 'Lexend', fontSize: '13px', width: `255px` }}
            transition={Flip}
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
      </body>
    </html>
  )
}
