import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/global.css'
import 'react-toastify/dist/ReactToastify.css'
import { Flip, ToastContainer } from 'react-toastify'
import Head from 'next/head'
// import FaviconImage from '../../public/images/favicon_travel.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className}>
        {children}
        <ToastContainer
          // style={{ fontFamily: 'Lexend', fontSize: '13px', width: `255px` }}
          transition={Flip}
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  )
}
